import=org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder;


spring.application.name=nativePlantTracker-api

spring.datasource.url=jdbc:postgresql://localhost:5432/Native_plants_DB
spring.datasource.username=postgres
spring.datasource.password=staple12
spring.datasource.driver-class-name=org.postgresql.Driver

# Optional JPA settings
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#Security
spring.security.user.name=admin
spring.security.user.password=$2a$10$pcFoZmOSS1rIT/VZzBJEDeWPnkctQter031Gr/HTvDYREEPp4NnwG

app.jwt-secret=bmF0aXZlUGxhbnRUcmFja2Vy
app.jwt-expiration-milliseconds=86400000